# Generated by Django 2.2.13 on 2020-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
