# Generated by Django 2.2.14 on 2020-07-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200709_0328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
