# Generated by Django 2.2.14 on 2020-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_authormodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
