# Generated by Django 3.0.8 on 2020-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_authormodel_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
